### ISSUE TITLE
Using a different technology?

### ISSUE THREAD

**Issue by bradysalz** [JulianYG/RedEye#1]
Hey there,

Was curious about adapting this for my own research with TSMC 65nm. Would I only need to change the numbers in `lib/energy.py`, or is there somewhere else I need to as well?

**Comment by JulianYG** [comment]
That's right, `energy.py` is the only file related to hardware modeling.

**Comment by bradysalz** [comment]
Awesome. Do you think there's value me or others submitting a PR with different technology/process nodes?

**Comment by JulianYG** [comment]
That would be great! You can put them under a directory with the name of the process.
